name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    env:
      BUILDOZER_ALLOW_ROOT: "1"
      PIP_BREAK_SYSTEM_PACKAGES: "1"

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show versions
        run: |
          python3 --version
          buildozer --version

      - name: Build Debug APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ExamDesignerPro
          path: bin/*.apk
