name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Force safe environment
        run: |
          export BUILDOZER_ALLOW_ROOT=1
          export PIP_BREAK_SYSTEM_PACKAGES=1

      - name: Build APK (no prompts)
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
